### ISSUE TITLE
Still not able to miniaturise Cooler

### ISSUE THREAD

**Issue by biship** [notfood/RimWorld-Miniaturisation#10]
https://github.com/notfood/RimWorld-Miniaturisation/issues/8

Maybe I misunderstood, so please let me know.
I started a new game without RedistHeat and still can not miniaturize the vanilla Cooler.

The only `<defName>Cooler</defName>` XML I have is from core: \RimWorld\Mods\Core\Defs\ThingDefs_Buildings\Buildings_Temperature.xml
(and none in any mod folder)

\RimWorld\Mods\RimWorld-Miniaturisation\Defs\MiniaturisationDefs\CoreExtra.xml contains `<li>Cooler</li>`

Am I doing something wrong? If there is a conflict, what else should I look for?

**Comment by notfood** [comment]
click uninstall. Some things that use certain comps require you to click uninstall.
