### ISSUE TITLE
Moved wind turbine is obstructed

### ISSUE THREAD

**Issue by RenaudF** [notfood/RimWorld-Miniaturisation#13]
After moving a wind turbine just one tile away, it was said to be "obstructed by wind turbine" even though it should have been clear.

I tried moving it somewhere else and it was also obstructed by random stuff that weren't there.

**Comment by DingoDjango** [comment]
This is a known issue with Wind Turbine code in general. If you exit and re-load the save it will refresh its obstruction check. It only does the hard commit once when it's built and once every time the game is loaded, if I recall correctly.

**Comment by RenaudF** [comment]
That's good to know. Thanks!

**Comment by notfood** [comment]
Yeah, can't do much about it.
